export { default as Section1 } from './Section1.svelte'
export { default as Section2 } from './Section2.svelte'
export { default as Section3 } from './Section3.svelte'
export { default as Section4 } from './Section4.svelte'
export { default as Section5 } from './Section5.svelte'
export { default as Section6 } from './Section6.svelte'